site_name: BTS SIO SLAM E6 - Révision
site_description: Programme de révision pour l'épreuve E6 du BTS SIO SLAM
site_author: Votre Nom
repo_name: ggaillard/BTS_SIO_EDC_SLAM_revisions
site_url: https://ggaillard.github.io/BTS_SIO_EDC_SLAM_revisions/

theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - navigation.top
    - navigation.tracking
    - content.tabs.link

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

plugins:
  - search
  - quizdown
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Accueil: index.md
  - Module 1 - Analyse des risques:
    - QCM de positionnement: Module1_AnalyseRisques/01_PositionnementQCM.md
    - Contenu du module: Module1_AnalyseRisques/02_Contenu.md
    - Auto-évaluation: Module1_AnalyseRisques/03_AutoEvaluationQCM.md
  - Module 2 - RGPD:
    - QCM de positionnement: Module2_RGPD/01_PositionnementQCM