site_name: BTS SIO SLAM E6 - Révision
site_description: Programme de révision pour l'épreuve E6 du BTS SIO SLAM
site_author: G.GAILLARD
site_url: https://votrecompte.github.io/BTS_SIO_EDC_SLAM_revisions/

# Configuration du thème
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

# Extensions Markdown
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.tasklist
  - pymdownx.details

# Plugins
plugins:
  - search
  - mermaid2
  - mkdocs-jupyter

# JavaScript supplémentaire pour MathJax et Pyodide
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.js
  - js/pyodide-init.js
  - js/custom-elements.js

# Feuilles de style supplémentaires
extra_css:
  - css/custom.css

# Structure de navigation

nav:
  - Accueil: index.md
  - M1 - Analyse des risques:
    - QCM de positionnement: Module1_AnalyseRisques/01_PositionnementQCM.md
    - Contenu du module: Module1_AnalyseRisques/02_Contenu.md
    - Auto-évaluation: Module1_AnalyseRisques/03_AutoEvaluationQCM.md
  - M2 - RGPD:
    - QCM de positionnement: Module2_RGPD/01_PositionnementQCM.md
    - Contenu du module: Module2_RGPD/02_Contenu.md
    - Auto-évaluation: Module2_RGPD/03_AutoEvaluationQCM.md
  - M3 - Authentification:
    - QCM de positionnement: Module3_Authentification/01_PositionnementQCM.md
    - Contenu du module: Module3_Authentification/02_Contenu.md
    - Auto-évaluation: Module3_Authentification/03_AutoEvaluationQCM.md
  - M4 - Sécurisation du code:
    - QCM de positionnement: Module4_SécurisationCode/01_PositionnementQCM.md
    - Contenu du module: Module4_SécurisationCode/02_Contenu.md
    - Auto-évaluation: Module4_SécurisationCode/03_AutoEvaluationQCM.md
  - M5 - Sécurité réseau:
    - QCM de positionnement: Module5_SécuritéRéseau/01_PositionnementQCM.md
    - Contenu du module: Module5_SécuritéRéseau/02_Contenu.md
    - Auto-évaluation: Module5_SécuritéRéseau/03_AutoEvaluationQCM.md
  - M6 - Gestion des incidents:
    - QCM de positionnement: Module6_GestionIncidents/01_PositionnementQCM.md
    - Contenu du module: Module6_GestionIncidents/02_Contenu.md
    - Auto-évaluation: Module6_GestionIncidents/03_AutoEvaluationQCM.md