name: Deploy to gh-pages

on:
  push:
    branches:
      - main  # ou la branche que tu utilises

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push changes to gh-pages
      run: |
        git add .
        git commit -m "Deploy updates"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}  # Utilisation du secret
